services:

  db:
    ports:
      - "7357:27017"

  bitcoin:
    ports:
      - "8332:8332"
      - "8333:8333"

  erigon:
    ports:
      - "9555:8545"

  geth:
    ports:
      - "9545:8545"
      - "9546:8546"
      - "40404:30303"

  rippled:
    ports:
      - "6996:6006"
