database:
  image: mongo:3.4-jessie
  ports: 
  - 27017:27017
  volumes: 
  - /data/db:/data/db
bitcore-node:
  image: bitcore-node
  links:
    - database
  ports:
    - 8100:8100
    - 3000:3000
  environment:
    - DB_HOST=database
    - TRUSTED_PEER='host.docker.internal'
    - TRUSTED_PEER_PORT=${TRUSTED_PEER_PORT}
#insight:
  #image: insight
  #links:
    #- bitcore-node
  #environment:
    #- API_URL=bitcore-node
