version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - /usr/local/var/mongodb:/data/db

  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    ports:
      - 3000:3000
      - 3232:3232
    environment:
      - DB_HOST=database
      - BWS_MONGODB_URI=mongodb://host.docker.internal:27017/bws
    env_file: .env

#insight:
  #image: insight
  #links:
    #- bitcore-node
  #environment:
    #- API_URL=bitcore-node
