version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports: 
    - 27017:27017
    volumes: 
    - /data/db:/data/db
    
  bitcore-node:
    build: .
    image: bitcore-node
    links:
      - database
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env

#insight:
  #image: insight
  #links:
    #- bitcore-node
  #environment:
    #- API_URL=bitcore-node
